libs/internal/include/launchdarkly/network/http_requester.hpp
libs/internal/src/network/http_requester.cpp

If we don't define the symbol, we don't need to undefine it.

chore: fix msvc compiler warnings related to strcasecmp

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/client-sdk/include/launchdarkly/client_side/client.hpp
libs/client-sdk/src/bindings/c/sdk.cpp
libs/client-sdk/src/client.cpp
libs/client-sdk/src/client_impl.cpp
libs/client-sdk/src/client_impl.hpp
libs/client-sdk/tests/client_c_bindings_test.cpp
libs/client-sdk/tests/client_test.cpp
release-please-config.json

Adds a `Version/LDClientSDK_Version`method, which exposes the client's version via function call.
In the previous way, it was a public static class member. This way, we have a bit more encapsulation and can also expose it via C binding.

feat: add Version method to obtain SDK version

---

README.md

We use Boost.URL, which was [introduced](https://www.boost.org/users/history/version_1_81_0.html) in 1.81.
Potentially we could switch to foxy's built-in URL library if we wanted to relax the boost requirement, although 1.81 came out in December 2022 so it's not exactly bleeding edge.

fix: update required Boost version to 1.81 for Boost.URL

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h

Adds missing `context` parameter to docs on `LDClientSDK_Identify`.

chore: fix docs on Identify c bindings

---

libs/common/include/launchdarkly/bindings/c/value.h
libs/common/src/bindings/c/value.cpp
libs/common/tests/bindings/value_test.cpp

Renames create/destroy object/array iterators to use new/free naming.

fix: rename C iterator bindings to follow new/free pattern

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/common/include/launchdarkly/bindings/c/array_builder.h
libs/common/include/launchdarkly/bindings/c/config/builder.h
libs/common/include/launchdarkly/bindings/c/config/config.h
libs/common/include/launchdarkly/bindings/c/context.h
libs/common/include/launchdarkly/bindings/c/context_builder.h
libs/common/include/launchdarkly/bindings/c/data/evaluation_detail.h
libs/common/include/launchdarkly/bindings/c/listener_connection.h
libs/common/include/launchdarkly/bindings/c/memory_routines.h
libs/common/include/launchdarkly/bindings/c/object_builder.h
libs/common/include/launchdarkly/bindings/c/status.h
libs/common/include/launchdarkly/bindings/c/value.h

Doxygen requires `@file` directives in files that contain global functions, which for us is the C bindings.

chore: add @file directive to C bindings

---

libs/client-sdk/src/data_sources/polling_data_source.cpp
libs/common/include/launchdarkly/config/shared/defaults.hpp

Enforces a minimum client-side polling interval of 5 minutes. The error message has been slightly updated for clarity.

fix: enforce minimum polling interval of 5 minutes

---

libs/client-sdk/src/client_impl.cpp
libs/common/include/launchdarkly/config/shared/builders/http_properties_builder.hpp
libs/common/src/config/http_properties_builder.cpp

Moves application tag into HTTP Config, so it can propagate to data sources + event sender.

fix: ensure x-launchdarkly-tags is sent in event requests

---

libs/common/include/launchdarkly/config/shared/built/data_source_config.hpp
libs/common/include/launchdarkly/config/shared/defaults.hpp

Adds / updates a couple of default config options in prep for server-side SDK.

chore: update server-side polling/streaming defaults

---

.github/actions/install-boost/action.yml
contract-tests/sdk-contract-tests/src/client_entity.cpp
libs/client-sdk/src/data_sources/data_source_event_handler.cpp
libs/internal/include/launchdarkly/network/asio_requester.hpp
libs/internal/include/launchdarkly/serialization/value_mapping.hpp
libs/internal/src/events/asio_event_processor.cpp
libs/internal/src/serialization/json_attributes.cpp
libs/internal/src/serialization/json_context.cpp
libs/internal/src/serialization/json_evaluation_reason.cpp
libs/server-sent-events/src/client.cpp
libs/server-sent-events/src/parser.hpp

This PR fixes compilation using boost 1.82.
It also fixes the CI issues from boost 1.81 being removed from brew, and floated with chocolatey.
Further changes, in another PR, will be needed to improve boost dependency robustness.

fix: Fix compilation with boost 1.82.

---

libs/client-sdk/src/data_sources/data_source_event_handler.cpp
libs/client-sdk/src/data_sources/data_source_update_sink.hpp
libs/client-sdk/src/flag_manager/flag_persistence.cpp
libs/client-sdk/tests/data_source_event_handler_test.cpp
libs/common/include/launchdarkly/attribute_reference.hpp
libs/common/src/attribute_reference.cpp
libs/internal/include/launchdarkly/data_model/item_descriptor.hpp
libs/internal/include/launchdarkly/data_model/sdk_data_set.hpp
libs/internal/include/launchdarkly/data_model/segment.hpp
libs/internal/include/launchdarkly/serialization/json_evaluation_result.hpp
libs/internal/include/launchdarkly/serialization/json_item_descriptor.hpp
libs/internal/include/launchdarkly/serialization/json_primitives.hpp
libs/internal/include/launchdarkly/serialization/json_sdk_data_set.hpp
libs/internal/include/launchdarkly/serialization/json_segment.hpp
libs/internal/include/launchdarkly/serialization/json_value.hpp
libs/internal/include/launchdarkly/serialization/value_mapping.hpp
libs/internal/src/CMakeLists.txt
libs/internal/src/data_model/sdk_data_set.cpp
libs/internal/src/serialization/json_evaluation_result.cpp
libs/internal/src/serialization/json_primitives.cpp
libs/internal/src/serialization/json_sdk_data_set.cpp
libs/internal/src/serialization/json_segment.cpp
libs/internal/src/serialization/json_value.cpp
libs/internal/src/serialization/value_mapping.cpp
libs/internal/tests/data_model_serialization_test.cpp
libs/internal/tests/evaluation_result_test.cpp

This PR extends our existing deserialization/serialization technique from the client-side SDK to the server-side SDK data model. 
Specifically, it adds deserialization for the segment structure. I've also introduced some helpers to make the logic less repetitive, and centralize some decisions (like what to do if a JSON field isn't present, or is null.)
As background, the `tag_invoke` functions present in this PR are what allows the `boost::json` library to recursively deserialize complex structures. 
Here, I've added a couple new `tag_invokes` for bool, string, vector, etc. The special part is that they deserialize into `expected<type, error>` rather than the primitive directly; this allows us to return an error if the deserialization failed.

feat: segment data model

---

libs/internal/include/launchdarkly/data_model/flag.hpp
libs/internal/include/launchdarkly/data_model/sdk_data_set.hpp
libs/internal/include/launchdarkly/data_model/segment.hpp
libs/internal/src/serialization/json_sdk_data_set.cpp
libs/internal/tests/data_model_serialization_test.cpp

Adds in missing `Flag` model to the top-level `SDKDataSet`.
I've also changed both the flag/segment fields to use `PARSE_FIELD`, so we can get an empty `unordered_map` if they are missing.

feat: add Flag model to SDKDataSet

---

.github/workflows/client.yml
.github/workflows/common.yml
.github/workflows/cpp-linter.yml
.github/workflows/internal.yml
libs/common/include/launchdarkly/config/shared/built/events.hpp
libs/internal/include/launchdarkly/serialization/json_primitives.hpp
libs/internal/include/launchdarkly/serialization/value_mapping.hpp
libs/internal/src/serialization/value_mapping.cpp

Also adds builds for server-side PRs.
I propose, in the future, we use a `feature/` convention.
Then we can add a `feature/**` filter for PR branches.

fix: Add various missing headers.

---

libs/common/include/launchdarkly/data/evaluation_reason.hpp
libs/common/src/data/evaluation_reason.cpp

This is the first in some attempts to break up the large evaluator PR. 
This commit adds new `EvaluationReason` constructors used within the evaluation engine.

feat: add more EvaluationReason constructors

---

libs/common/include/launchdarkly/value.hpp
libs/common/src/value.cpp

Adds `<`, `>`, `<=`, and `>=` to `Value`. These are used within rule match logic in the evaluation engine.
They don't attempt to do any special lexical comparisons or anything like that - non-numbers always return false.

feat: add comparison operators to Value

---

cmake/rfc3339_timestamp.cmake
libs/server-sdk/CMakeLists.txt
libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/evaluation/detail/timestamp_operations.cpp
libs/server-sdk/src/evaluation/detail/timestamp_operations.hpp
libs/server-sdk/tests/CMakeLists.txt
libs/server-sdk/tests/timestamp_tests.cpp

Adds the ability to parse timestamps from string or numeric `Value`s. 
This uses the same RFC3339 parser from the C Server SDK, so results should be consistent.

feat: timestamp parsing from Values

---

libs/internal/include/launchdarkly/encoding/base_16.hpp
libs/internal/include/launchdarkly/encoding/sha_1.hpp
libs/internal/src/CMakeLists.txt
libs/internal/src/encoding/sha_1.cpp
libs/internal/src/encoding/sha_256.cpp
libs/internal/tests/sha_1_test.cpp
libs/internal/tests/sha_256_test.cpp

Adds a new `sha1` hash function, implemented similar to the existing `sha256`. 
I've also extracted the hex encoding routine from sha256's tests into a dedicated header so it can be reused in sha1's tests or elsewhere.

feat: add sha1 hashing  and base16 encoding routines

---

libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/evaluation/detail/evaluation_stack.cpp
libs/server-sdk/src/evaluation/detail/evaluation_stack.hpp
libs/server-sdk/tests/evaluation_stack_test.cpp

Adds a data structure for detecting circular references during evaluation. It is called `EvaluationStack` and uses RAII to notice/forget keys. 
Intended usage is like:
```c++
if (auto guard = stack.SeenPrerequisite("foo")) {
// Now "foo" has been seen. Can't obtain another guard until this one is destroyed.
assert_false(stack.SeenPrerequisite("foo"))
}
```

feat: evaluation stack for detecting cyclic references

---

libs/common/include/launchdarkly/context.hpp
libs/common/include/launchdarkly/detail/c_binding_helpers.hpp
libs/common/src/context.cpp
libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/evaluation/bucketing.cpp
libs/server-sdk/src/evaluation/bucketing.hpp
libs/server-sdk/src/evaluation/evaluation_error.cpp
libs/server-sdk/src/evaluation/evaluation_error.hpp
libs/server-sdk/tests/bucketing_tests.cpp

Adds bucketing logic to be used in evaluation engine. 
Buckets are computed based on a hash value comprised of context attributes and prefixes derived from flag rules.

feat: context bucketing logic

---

libs/server-sdk/src/evaluation/bucketing.cpp
libs/server-sdk/src/evaluation/evaluator.cpp

Removes potentially costly, unecessary copies of `Value` in the evaluation algorithm.

fix: avoid copying Value in Evaluator algorithm

---

libs/internal/include/launchdarkly/data_model/context_aware_reference.hpp
libs/internal/include/launchdarkly/data_model/context_kind.hpp
libs/internal/include/launchdarkly/data_model/flag.hpp
libs/internal/include/launchdarkly/serialization/json_context_aware_reference.hpp
libs/internal/include/launchdarkly/serialization/json_context_kind.hpp
libs/internal/src/CMakeLists.txt
libs/internal/src/serialization/json_context_kind.cpp
libs/internal/src/serialization/json_flag.cpp
libs/internal/tests/data_model_serialization_test.cpp
libs/server-sdk/tests/dependency_tracker_test.cpp

Previously, context kind was an `std::string`. 
The requirement that it not be an empty string was enforced by parent data model deserializers. 
Now, we have a dedicated type-safe wrapper via`BOOST_STRONG_TYPEDEF`. The custom `tag_invoke` enforces the invariant so it's not possible to deserialize it inconsistently.

feat: add ContextKind type to data model

---

libs/server-sdk/src/evaluation/detail/evaluation_stack.cpp
libs/server-sdk/src/evaluation/detail/evaluation_stack.hpp
libs/server-sdk/src/evaluation/evaluation_error.hpp

Current API of `EvaluationStack` is very easy to accidentally misuse because it takes a reference to its key argument. If the arg is destroyed, then we'll have a use-after-free.

fix: EvaluationStack should take ownership of key argument

---

architecture/event_processor.md
libs/internal/include/launchdarkly/events/detail/outbox.hpp
libs/internal/include/launchdarkly/events/detail/summarizer.hpp
libs/internal/src/events/outbox.cpp
libs/internal/src/events/summarizer.cpp
libs/internal/src/serialization/events/json_events.cpp
libs/internal/tests/event_summarizer_test.cpp

Also fixes some style / const-correct issues that I found while documenting.

chore: add event processor architectural diagrams

---

.github/workflows/server.yml
libs/common/include/launchdarkly/attribute_reference.hpp
libs/internal/include/launchdarkly/data_sources/data_source_status_manager_base.hpp
libs/internal/src/serialization/json_flag.cpp
libs/internal/src/serialization/json_rule_clause.cpp
libs/internal/src/serialization/json_sdk_data_set.cpp
libs/internal/src/serialization/json_segment.cpp
libs/server-sdk/src/data_sources/streaming_data_source.cpp
libs/server-sdk/src/data_store/dependency_tracker.hpp
libs/server-sdk/src/data_store/persistent/expiration_tracker.hpp
libs/server-sdk/src/evaluation/bucketing.cpp
libs/server-sdk/src/evaluation/bucketing.hpp
libs/server-sdk/src/evaluation/operators.cpp
libs/server-sdk/tests/operator_tests.cpp
libs/server-sdk/tests/rule_tests.cpp
libs/server-sdk/tests/timestamp_tests.cpp

Adds a build for the server SDK. The changes are mostly to fix compilation issues / warnings that I encountered.

feat: build server SDK in CI

---

CMakeLists.txt

Our documented minimum version of boost is 1.81. The `CMakeLists.txt` erroneously specified 1.80, which could potentially lead to 1.80 being selected and the build failing.
This commit bumps it to 1.81, which includes the necessary `url` library.

chore: update boost version in CMakeLists.txt

---

examples/CMakeLists.txt
examples/hello-c-client/CMakeLists.txt
examples/hello-cpp-client/CMakeLists.txt
examples/hello-cpp-server/CMakeLists.txt
examples/hello-cpp-server/main.cpp

Adds a hello app for the Server-side SDK.
I modified the existing apps to fix CMake target name conflicts.

feat: hello-cpp-server

---

contract-tests/server-contract-tests/test-suppressions.txt
libs/internal/include/launchdarkly/data_model/flag.hpp
libs/internal/src/serialization/json_flag.cpp
libs/internal/tests/data_model_serialization_test.cpp
libs/server-sdk/src/evaluation/bucketing.cpp

Fixes handling of undefined variations in VariationOrRollout structures. Previously, the lack of a variation was treated as 0, as I had assumed the normal data model rules apply. 
Instead, there is a special case that variation _must_ be defined or else a flag is malformed.

fix: handle undefined flag variations in fallthrough

---

.github/actions/sdk-release/action.yml
.github/workflows/manual-client-release-artifacts.yml
.github/workflows/release-please.yml

The intention is to be able to reuse `actions/client-release` for the server-side SDK.It currently has hardcoded paths and CMake targets for the client-side SDK.
To make it generic, I've added new inputs for specifying those parameters.
I'm not 100% sure this is the best way to achieve my goal, but it seems relatively straightforward.

chore: refactor client-release action to support server-side SDK

---

.github/workflows/manual-sdk-release-artifacts.yml

Looking at my test run, I believe the outputs aren't actually made available to the release job the way I had it setup - just echoing to `$GITHUB_OUTPUTS`.
The documentation is rather [sparse](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs), but looks like we need an `outputs` map.

chore: plumb outputs from split-input to release-sdk job

---

libs/server-sdk/src/client_impl.cpp
libs/server-sdk/src/client_impl.hpp

This removes a bunch of duplicated work from the top-level typed Variation methods, and pushes it into the internal `Variation` method. 
To support this, I needed to hoist the `VariationDetail` method into the header and make it generic.

refactor: push typechecking of variation methods deeper down

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/client-sdk/src/bindings/c/sdk.cpp
libs/client-sdk/tests/client_c_bindings_test.cpp
libs/common/include/launchdarkly/bindings/c/flag_listener.h
libs/common/src/CMakeLists.txt
libs/common/src/bindings/c/flag_listener.cpp

This commit moves the definition and implementation of `LDFlagListener` into `common`, so it can be easily shared with the server.
Additionally, it fixes a bug in the specification of the `LDFlagListener_Init` method. It previously took `LDFlagListener` by value; now it takes a pointer. 
The impact would be if a customer forgot to initialize the struct, then the member(s) would be undefined.

fix: initialization of LDFlagListener 

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/client-sdk/src/bindings/c/sdk.cpp
libs/client-sdk/tests/client_c_bindings_test.cpp

This function previously took `LDDataSourceStatusListener` by value; now it takes a pointer.
The impact would be if a customer forgot to initialize the struct, then the member(s) would be undefined.
Found this after finding similar https://github.com/launchdarkly/cpp-sdks/pull/218. Following that PR, it will be released as a bugfix patch.

fix: LDDataSourceStatusListener_Init should take pointer

---

libs/internal/src/serialization/json_value.cpp

We had an infinite loop where the `Value` tag invoke deserializer was calling the `tl::expected<Value, JsonError` version, which called back to itself.
This was manifesting as a runtime infinite loop. 
It's not caught by contract tests since I believe the trigger is having a list of variations that are themselves arrays, like:
```
"variations": [["a","b","c",123,true,"false"], [ .. other stuff ..], ... ]
```
The fix is to break the cycle and remove the incorrect implementation.

fix: deserializing certain values leads to infinite loop

---

libs/server-sdk/include/launchdarkly/server_side/client.hpp
libs/server-sdk/src/client.cpp
libs/server-sdk/src/client_impl.cpp
libs/server-sdk/src/client_impl.hpp

This was commented out / not present in the API before, but the implementation is now in the client so we just need expose it.

feat: add DataSourceStatus() and plumb through IClient interface

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/client-sdk/src/bindings/c/sdk.cpp
libs/common/include/launchdarkly/bindings/c/data_source/error_info.h
libs/common/include/launchdarkly/bindings/c/data_source/error_kind.h
libs/common/include/launchdarkly/data_sources/data_source_status_error_info.hpp
libs/common/include/launchdarkly/data_sources/data_source_status_error_kind.hpp
libs/common/src/CMakeLists.txt
libs/common/src/bindings/c/data_source/error_info.cpp

This moves all the `_ErrorInfo_` C bindings out of the client-side SDK and into the common library, allowing them to be shared with the server.
This should be backwards compatible because the `sdk.h` includes the new `error_info.h`, providing the same symbols as before.

refactor: move DataSourceStatus ErrorInfo C Bindings into common

---

contract-tests/sdk-contract-tests/src/entity_manager.cpp
libs/client-sdk/src/data_sources/streaming_data_source.cpp
libs/server-sent-events/include/launchdarkly/sse/client.hpp
libs/server-sent-events/src/client.cpp

The public API was already available, but we didn't have the plumbing required to get it into the SSE client. Therefore, I'm regarding it as a bugfix. 
This came up because we need it to pass some streaming contract tests, which in part fail because our default delays are too high (starting at 1 second).

fix: allow for specification of initial reconnect delay in streaming data source

---

examples/CMakeLists.txt
examples/client-and-server-coexistence/CMakeLists.txt
examples/client-and-server-coexistence/main.c
examples/hello-c-client/main.c
examples/hello-c-server/CMakeLists.txt
examples/hello-c-server/main.c
examples/hello-cpp-server/main.cpp
libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/client-sdk/src/bindings/c/sdk.cpp
libs/client-sdk/tests/client_c_bindings_test.cpp
libs/common/include/launchdarkly/bindings/c/shared_function_argument_macro_definitions.h
libs/common/include/launchdarkly/config/client.hpp
libs/common/include/launchdarkly/config/server.hpp
libs/server-sdk/include/launchdarkly/server_side/bindings/c/all_flags_state/all_flags_state.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/config.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/sdk.h
libs/server-sdk/include/launchdarkly/server_side/client.hpp
libs/server-sdk/include/launchdarkly/server_side/data_source_status.hpp
libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/bindings/c/all_flags_state/all_flags_state.cpp
libs/server-sdk/src/bindings/c/builder.cpp
libs/server-sdk/src/bindings/c/config.cpp
libs/server-sdk/src/bindings/c/sdk.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp

This implements a set of C bindings for the server-side SDK. 
Missing are flag notifier bindings, but this isn't implemented in the C++ side yet either.

feat: server-side C bindings

---

contract-tests/server-contract-tests/src/entity_manager.cpp
contract-tests/server-contract-tests/test-suppressions.txt
libs/server-sdk/src/data_sources/streaming_data_source.cpp

Hooks up the initial reconnect delay parameter to the server-side streaming data source. Allows us to remove another batch of contract test failures.

feat: plumb server side initial backoff delay

---

libs/client-sdk/package.json
libs/common/package.json

Currently we have:
```
client-sdk -> common -> sse-client
```
The `common` lib doesn't depend on `sse-client`, so this results in unnecessary `common` revisions. 
This commit makes `sse-client` a dependency of `client-sdk`.

refactor: move sse-client package dep from common to client-sdk

---

libs/common/src/config/app_info_builder.cpp

The argument to `ValidChar` is a `char`, so its max value is `255` rendering the check redundant. This causes a warning on our Mac compilations as well as a linter warning. 
(unless we have a platform that has a char wider than 8 bits..)

chore: resolve ValidChar function lint/compile warnings

---

.github/actions/sdk-release/action.yml
.github/workflows/release-please.yml

Using [generic SLSA provenance generator ](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#a-different-attestation-for-each-iteration) to build provenance attestations for our client SDK artifacts. [Tech spec for reference ](https://launchdarkly.atlassian.net/wiki/spaces/SEC/pages/2529919025/Integrating+SLSA+compliance+with+SDK+release+workflows#Provenance-only-generator)
Since we're using a matrix strategy for the build, there will be one attestation file for all the artifacts for each platform (i.e., attestation for Linux artifacts, one for Windows artifacts, one for MacOS artifacts). 
Based off of POC here: https://github.com/launchdarkly/learn-release-please/pull/35/files though this time it should be more accurate since we're …

fix: adding slsa provenance generation to release-client workflow

---

.github/workflows/manual-sdk-release-artifacts.yml

Follow up to https://github.com/launchdarkly/cpp-sdks/pull/212 to add release provenance when release is manually generated

fix: adding provenance generation to manual publish workflow

---

.github/actions/sdk-release/action.yml
.github/workflows/manual-sdk-release-artifacts.yml
.github/workflows/release-please.yml

`shasum` has different parameters in MacOS vs Linux/Windows:
```
Run echo "hashes-macos=$(sha256sum mac-clang-x64-static.zip mac-clang-x64-dynamic.zip | base64 -w0)" >> "$GITHUB_OUTPUT"
/Users/runner/work/_temp/8965ab70-9f6a-4960-9224-3651a6a4797a.sh: line 1: sha256sum: command not found
base64: invalid option -- w
Usage:	base64 [-hvDd] [-b num] [-i in_file] [-o out_file]
```
Changing this to `base64 -b 0` should fix it and get the intended result

fix: shasum generation for macos artifacts + uploading provenance to Github release

---

libs/common/src/config/app_info_builder.cpp

This is a cherry-pick from a PR already merged on `server-side` branch.

chore: resolve ValidChar function lint/compile warnings (#234)

---

contract-tests/sse-contract-tests/include/event_outbox.hpp
contract-tests/sse-contract-tests/src/entity_manager.cpp
contract-tests/sse-contract-tests/src/event_outbox.cpp
contract-tests/sse-contract-tests/src/main.cpp
libs/client-sdk/src/data_sources/streaming_data_source.cpp
libs/common/src/config/logging_builder.cpp
libs/server-sent-events/include/launchdarkly/sse/client.hpp
libs/server-sent-events/include/launchdarkly/sse/error.hpp
libs/server-sent-events/src/client.cpp
vendor/foxy/include/foxy/impl/session/async_read.impl.hpp
vendor/foxy/include/foxy/session.hpp

This fixes [streaming connection dropping after 5 minutes](https://github.com/launchdarkly/cpp-sdks/issues/243). 
The problem was applying a 5 minute timeout to an `async_read` _operation_, when the actual intent was to apply it to the act of receiving _any data_. 
The timeout exists to prevent the client from hanging infinitely if the server stops responding. LaunchDarkly sends heartbeats to clear the timer.
With `async_read`, the operation won't complete until the response body is finished. Since the body will never finish until the client shuts down (or server interrupts it), it's not possible to institute a timeout. 
The solution is to use `async_read_some`, which completes whenever data arrives.
This way, we can assign the 5 minute timeout as an upper bound on receiving any data, as …

fix: stream connections longer than 5 minutes are dropped 

---

.github/actions/sdk-release/action.yml
.github/workflows/manual-sdk-release-artifacts.yml
.github/workflows/release-please.yml

Adding `-provenance` suffix to make the provenance artifacts clearer to consumers. Additionally, renaming `macos-` prefix to `mac-` to match the prefix of the mac build artifacts, per guidance from https://slsa.dev/spec/v1.0/distributing-provenance#relationship-between-artifacts-and-attestations

build: slight renaming of provenance output to meet best practice

---

.github/ISSUE_TEMPLATE/client-sdk--bug-report.md

Now that `LD_LOG_LEVEL` environment variable works as expected, we should call this out in the bug report template. This will aid in gathering more useful debug logs or lead to resolution without further analysis. 
Example:
```
LD_LOG_LEVEL=debug ./application-that-uses-sdk
```

docs: update bug report instructions

---

.github/actions/sdk-release/action.yml
.github/workflows/client.yml
CMakeLists.txt

We were previously using openssl 1.1 on some platforms due to issues with the Github Actions executors.
These issues are no longer present, so we can use openssl > 3 instead. 
_(created story for removing the choco upgrade in Windows once Github releases a new runner)_

fix: build with OpenSSL > 3.0 on all platforms

---

libs/internal/include/launchdarkly/events/parse_date_header.hpp
libs/internal/include/launchdarkly/events/request_worker.hpp
libs/internal/include/launchdarkly/events/worker_pool.hpp
libs/internal/src/events/request_worker.cpp
libs/internal/src/events/worker_pool.cpp
libs/internal/tests/event_processor_test.cpp

The event delivery subsystem inspects the HTTP headers on the event endpoints whenever it posts a batch of events.
It parses out the date header, storing it for later use. When emitting debug events, it is used to ensure that events stop emitting even if the host's time is off - as a form of time synchronization.
The parsing code is quite ugly, and also wrong - it assumed that `en_US.utf-8` would always be available. 
This commit hoists the locale loading routine out of the individual flush-workers and into the worker pool. If it can't load the locale, it emits a single `warn` log at startup explaining the effect.

fix: catch exception if en_US.utf8-locale missing when parsing datetime headers

---

.github/actions/sdk-release/action.yml
.github/workflows/client.yml
.github/workflows/manual-sdk-release-artifacts.yml

We have intermittent CI failures because OpenSSL is installed to either `Program Files\OpenSSL-Win64` or `Program Files\OpenSSL`. I'm not entirely sure why, but it seems to be luck of the draw on the runner.
This should detect where it was installed and pass it to CMake. 
We can't force the install location because that requires a licensed chocolatey. Chocolatey also writes out the install location - for this particular package - but we'd have to process its output. Instead, this just tests the two known installation directories.

chore: detect where OpenSSL is installed on Windows runner

---

.clang-format
cmake/expected.cmake
libs/client-sdk/src/bindings/c/builder.cpp
libs/client-sdk/src/data_sources/streaming_data_source.cpp
libs/common/include/launchdarkly/attributes.hpp
libs/common/include/launchdarkly/bindings/c/value.h
libs/common/include/launchdarkly/detail/c_binding_helpers.hpp
libs/common/include/launchdarkly/detail/unreachable.hpp
libs/common/include/launchdarkly/value.hpp
libs/common/src/attribute_reference.cpp
libs/common/src/bindings/c/data/evaluation_detail.cpp
libs/common/src/bindings/c/value.cpp
libs/common/src/value.cpp
libs/internal/include/launchdarkly/network/asio_requester.hpp
libs/internal/src/CMakeLists.txt
libs/internal/src/serialization/json_value.cpp
scripts/build.sh

Many users might compile the SDK using a "warnings as errors" flag. 
It would be helpful to enable that flag in our CI, such that we can be relatively sure that the SDK compiles w/o warnings on major compilers.

fix: treat warnings as errors in CI

---

CMakeLists.txt

The dependent arguments in `cmake_dependent_option` need to be quoted (list). Otherwise, it seems the behavior is incorrect.
In this case, a release failed because `BUILD_TESTING=Off` didn't actually turn off the `LD_BUILD_UNIT_TESTS` variable. I've tested locally and it now works as expected.

fix: cmake_dependent_option needs list argument

---

CMakeLists.txt
cmake/certify.cmake
libs/client-sdk/src/CMakeLists.txt

In my previous PR cleaning up cmake variables, during development I renamed the `BUILD_SHARED_LIBS` flag to `BUILD_STATIC_LIBS`, but then reconsidered and stuck with the original naming.
Unfortunately I didn't un-rename some usages of it - so we ended up having some instances of `LD_BUILD_STATIC_LIBS` in our `CMakeLists.txt`.
It appears this didn't have an obvious impact on our build/release process because:
1) Since `NOT LD_BUILD_STATIC_LIBS` would always be true (variable not defined), then it would have been setting `-fvisibility=hidden` on both shared and static builds. I'm pretty sure that flag has no affect when building static libs so it was a no-op in that situation.
2) Using the `target_sources` trick for pulling in the boost libraries always works whether we're building static …

fix: LD_BUILD_SHARED_LIBS build flag usage

---

libs/internal/include/launchdarkly/data_model/segment.hpp
libs/internal/include/launchdarkly/serialization/json_context_kind.hpp
libs/internal/include/launchdarkly/serialization/value_mapping.hpp
libs/internal/src/serialization/json_context_kind.cpp
libs/internal/src/serialization/json_segment.cpp
libs/internal/tests/data_model_serialization_test.cpp

Resolves an outstanding TODO in `server-side` by enforcing segments to deserialize with valid context kinds.

fix: enforce validated ContextKind usage in Segment data model

---

CMakeLists.txt

There's no point trying to build contract tests when building the SDK as a shared lib, since we don't expose a C++ ABI (get a bunch of undefined symbol errors.)
Can also remove the warning message that I had previously - it's not actually necessary if you use `cmake_dependent_option` correctly!

build: disallow contract tests when building shared libs

---

libs/client-sdk/tests/client_test.cpp

Adds a unit test that should catch if we make a breaking change to the types accessible via `client.DataSourceStatus()`.
This is useful because the upcoming server-side SDK refactors the Data Source Status types into the common library, and we must therefore provide aliases in the client SDK.

chore: add data source status backwards-compat unit test

---

CMakeLists.txt
libs/client-sdk/src/CMakeLists.txt
libs/server-sdk/src/CMakeLists.txt

Latest client release failed because I failed to consider that the `install` step currently requires all artifacts (both client, and now server) to be built. Since we use `cmake --build . --target "$clientOrServer"`, it failed on the install step because server isn't built.
This commit makes installation optional for either.

fix: allow for installing only the client or server SDK independently

---

.github/workflows/manual-publish-doc.yml
.github/workflows/manual-sdk-release-artifacts.yml
.release-please-manifest.json
libs/server-sdk/CMakeLists.txt
libs/server-sdk/package.json
release-please-config.json

Adds the server-side SDK into release please @ `0.1.0`. I've marked `prerelease: true`, so it should be marked as such when we do a Github release.

chore: add server-side SDK to release-please config

---

.release-please-manifest.json
libs/server-sdk/package.json
release-please-config.json

This is an attempt to fix the pending release. 
Ideally, release please would detect that no release is necessary or that a 0.1.0 initial release of the server side only is necessary.
Right now, it thinks that the `sse-client` needs a release, and it's therefore bumping that and the server/client SDKs.

chore: remove server-side version from release-please manifest

---

release-please-config.json

It appears release-please is looking far back in history when determining the release version of the server package. During this search, it also appears to be running into a SSE commit that didn't use conventional commit formatting.
Now, it's unclear if this is connected - but it might be making release-please think that an SSE bump is required.
My theory is that by limiting to 10 commits (not sure how low this could be - 0?) we can eliminate the issue. This should be ok since we know for a fact no conventional commits have happened to SSE client that would affect the server. 
This all feels rather unintuitive though. I'd like to keep digging but this is becoming a time sink.

chore: limit commit-search-depth to 10 for server-side package

---

release-please-config.json

chore: revert commit depth specification on libs/server-sdk

---

.github/workflows/release-please.yml

When I merged the release-please PR for server, the Github release was created but artifacts were not generated.
That's because I forgot to add the server jobs to `release-please`'s main action.
I'm hoping to re-run the last release-please action which will pick this up.

chore: update release-please.yml with server-sdk

---

.github/actions/ci/action.yml
.github/actions/install-openssl/action.yml
.github/workflows/client.yml

Setting up the correct OpenSSL version should be encapsulated in the `ci` action, but it leaked out when I added the code to ensure OpenSSL > 3 on all runners.
Putting it back in its place. Motivated because I'm making another action that could use this.

chore: refactor openssl setup into dedicated x-platform action

---

.github/actions/ci/action.yml
.github/workflows/client.yml
.github/workflows/server.yml

Right now our release process isn't tested on every commit - if the release fails due to a build issue, we need to make a new release.
This commit runs `./build-release` in our Linux CI step. It's not building docs nor running on all types executors, but I think this is a good compromise to catch 99% of issues that might occur.

chore: run build-release.sh in client/server CI

---

.github/actions/install-boost/action.yml
.github/actions/install-openssl/action.yml

In our "install OpenSSL" CI step, I hadn't properly setup the "return values" - setting the `OPENSSL_ROOT_DIR` properly. 
The builds still mostly worked, but were fragile. This is due to CMake's find modules finding them anyways. Except when they don't!

chore: set OpenSSL root dir properly in CI

---

release-please-config.json

Noticed on the release PR that the server's version hasn't changed, which makes sense because I didn't remove `release-as` yet. This removes it.

chore: remove 'release-as' from server sdk

---

libs/server-sdk/include/launchdarkly/server_side/config/builders/all_builders.hpp
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/background_sync_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/bootstrap_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/data_destination_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/data_system_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/lazy_load_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/all_built.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/background_sync_config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/bootstrap_config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/data_destination_config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/data_system_config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/lazy_load_config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/config_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/defaults.hpp
libs/server-sdk/src/config/builders/data_system/background_sync_builder.cpp
libs/server-sdk/src/config/builders/data_system/bootstrap_builder.cpp
libs/server-sdk/src/config/builders/data_system/data_destination_builder.cpp
libs/server-sdk/src/config/builders/data_system/data_system_builder.cpp
libs/server-sdk/src/config/builders/data_system/defaults.hpp
libs/server-sdk/src/config/builders/data_system/lazy_load_builder.cpp
libs/server-sdk/src/config/config.cpp
libs/server-sdk/src/config/config_builder.cpp
libs/server-sdk/tests/config_builder_test.cpp

This introduces a set of configuration objects & builders for the server-side Data System.
These are defined in `libs/server-sdk` rather than in common, since they don't apply to the client at the moment. In a future client major version, we could attempt to unify them.

feat: data system config builders [3]

---

contract-tests/client-contract-tests/src/entity_manager.cpp
contract-tests/server-contract-tests/src/entity_manager.cpp
libs/common/include/launchdarkly/config/shared/built/data_source_config.hpp
libs/common/include/launchdarkly/error.hpp
libs/common/src/error.cpp
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/lazy_load_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/data_interfaces/sources/iserialized_data_reader.hpp
libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/bindings/c/builder.cpp
libs/server-sdk/src/bindings/c/sdk.cpp
libs/server-sdk/src/config/builders/data_system/background_sync_builder.cpp
libs/server-sdk/src/config/builders/data_system/defaults.hpp
libs/server-sdk/src/config/builders/data_system/lazy_load_builder.cpp
libs/server-sdk/src/data_components/kinds/kinds.hpp
libs/server-sdk/src/data_components/serialization_adapters/json_data_reader.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.hpp
libs/server-sdk/src/data_systems/lazy_load/lazy_load_system.cpp
libs/server-sdk/src/data_systems/lazy_load/lazy_load_system.hpp
libs/server-sdk/tests/config_builder_test.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp

This fixes a bunch of compiler errors on the `feat/data-system` branch, which existed because of the piecemeal manner in which I broke out chunks from my working Redis client branch.

build: fix compilation errors in data system

---

libs/server-sdk/src/data_systems/background_sync/sources/streaming/event_handler.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/event_handler.hpp

Just removes a verbose namespace prefix that isn't necessary.

refactor: remove redundant namespacing in streaming event_handler

---

libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h

Must've been a copy paste error.

docs: substitute 'client' for 'server' in server-side Config Builder bindings

---

contract-tests/client-contract-tests/src/entity_manager.cpp
libs/client-sdk/src/client_impl.cpp
libs/client-sdk/src/client_impl.hpp
libs/client-sdk/src/data_sources/data_source.hpp
libs/client-sdk/src/data_sources/data_source_event_handler.hpp
libs/client-sdk/src/data_sources/null_data_source.hpp
libs/client-sdk/src/data_sources/polling_data_source.hpp
libs/client-sdk/src/data_sources/streaming_data_source.hpp

This is a mostly removing a bunch of redundant namespace qualifiers + formatting changes in the client SDK, which I addressed while building the Redis integration.
We can merge these directly to main instead to make the Redis PR cleaner.

refactor: various client SDK lints

---

libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/data_system_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/lazy_load_config.hpp
libs/server-sdk/include/launchdarkly/server_side/config/config_builder.hpp
libs/server-sdk/src/bindings/c/builder.cpp
libs/server-sdk/src/bindings/c/sdk.cpp
libs/server-sdk/src/config/builders/data_system/data_system_builder.cpp
libs/server-sdk/src/config/builders/data_system/defaults.hpp
libs/server-sdk/src/config/builders/data_system/lazy_load_builder.cpp
libs/server-sdk/src/config/config.cpp
libs/server-sdk/src/config/config_builder.cpp
libs/server-sdk/tests/config_builder_test.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp
libs/server-sdk/tests/service_endpoint_builders_test.cpp

This adds in some missing top-level Data System builder methods, as well as additional documentation. 
Some config tests that I previously removed from the `common` lib are added back into the server. 
I've also re-added Offline mode configuration, which modifies Data System and Events configuration.

feat: implement additional data system config builders

---

libs/server-sdk/src/data_components/expiration_tracker/expiration_tracker.cpp
libs/server-sdk/src/data_components/expiration_tracker/expiration_tracker.hpp

Removes some redundant namespace prefixes in `expiration_tracker` to make the code more readable.

refactor: remove redundant namespaces in expiration tracker

---

libs/server-sdk/include/launchdarkly/server_side/data_interfaces/sources/iserialized_data_reader.hpp
libs/server-sdk/src/data_interfaces/source/idata_synchronizer.hpp
libs/server-sdk/src/data_systems/background_sync/background_sync_system.cpp
libs/server-sdk/src/data_systems/background_sync/sources/noop/null_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/noop/null_data_source.hpp
libs/server-sdk/src/data_systems/background_sync/sources/polling/polling_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/polling/polling_data_source.hpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.hpp

This refactors `IDataSynchronizer` to take an `IDestination`  and bootstrap data in its `StartAsync` method, rather than having an independent `Init` function.
The addition of `IDestination` makes the interface's purpose clearer.
Before the destination was hidden - you'd only see it when constructing an implementation. Now it's clear that the `IDataSynchronizer` puts data into the `IDestination`; no hidden dependency.
It also doesn't make sense to "Init" an `IDataSynchronizer` with an SDKDataSet. 
The purpose of that call is to allow the synchronizer to inspect any existing data in possession by the SDK. The result of that inspection might mean an optimized fetch of initial data is possible (e.g. if there was an etag present in the initial data.)

refactor: improve IDataSynchronizer's interface to expose IDestination

---

libs/internal/include/launchdarkly/serialization/value_mapping.hpp
libs/internal/src/serialization/json_flag.cpp
libs/internal/src/serialization/json_segment.cpp
libs/internal/tests/data_model_serialization_test.cpp

The server-side SDK is able to treat missing JSON fields as empty ones in-memory. 
For example, in a segment if `included` was missing then the SDK infers it's an empty array. 
This change makes the SDK write out data using that same logic. If an in-memory field is conceptually empty, then omit it from the written data. 
This is an optimization, so I haven't audited all data models to enforce this behavior - the places I've updated are things I'm using in unit tests where I'd like to omit missing (irrelevant for the test) fields.

feat: omit empty items from data model JSON serialization

---

CMakeLists.txt
README.md
libs/client-sdk/src/CMakeLists.txt
libs/client-sdk/src/boost.cpp
libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/boost.cpp

Boost 1.83 introduced a change where `boost.url` needs to be linked in. 
We had a goal of hiding boost when building our shared libraries. Previously, we did this by including boost.json and boost.url headers in `boost.cpp`.
Now, we need to link in the compiled libraries but this poses a problem when we produce our shared library - the ones we fetch for Linux weren't compiled with `-fPIC`. We could setup some custom repo of artifacts built with that option, but I think that is too much of a lift.
Instead, we can change our strategy: when instructed to produce shared libs, we can link boost dynamically by default.
Provided is a new `LD_DYNAMIC_LINK_BOOST` flag to revert this behavior and find static boost libs instead.

build: dynamically link boost when producing shared libraries

---

cmake/json.cmake

Resolves a longstanding cmake bug in nlohmann/json.

chore(deps): bump nlohmann/json from 3.11.2 to 3.11.3

---

libs/server-sdk/src/data_components/expiration_tracker/expiration_tracker.cpp
libs/server-sdk/tests/expiration_tracker_test.cpp

Current usage of `assign` will be a no-op if the expiry for an existing item is added.

fix: use insert_or_assign in expiration tracker

---

.github/workflows/server.yml

This cruft can be removed now that the OpenSSL stuff is fully encapsulated in the `install-openssl` action.

build: remove obsolete OpenSSL config in server.yml

---

.github/workflows/release-please.yml
libs/server-sdk-redis-source/include/launchdarkly/server_side/integrations/redis/redis_source.hpp
release-please-config.json

This sets `release-as: 1.0` for the Redis source.
It also fixes a copy/paste error in `release-please.yml` that caused the Redis Source to attempt to run a release when it wasn't necessary.
I've made a arbitrary but useful change in `redis_source.hpp` so it's a releasable unit.

feat: redis source 1.0

---

.github/workflows/release-please.yml

Adds provenance generation to the server SDK's redis integration releases.

ci: add provenance to redis source releases

---

.github/workflows/lint-pr-title.yml

Use launchdarkly lint-pr-title workflow.

ci: use shared lint-pr-title workflow

---

libs/server-sdk/include/launchdarkly/server_side/bindings/c/sdk.h
libs/server-sdk/src/bindings/c/sdk.cpp
libs/server-sdk/tests/client_test.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp

The C bindings for `DoubleVariation/Detail` were returning `int` instead of `double`. 
Since this is totally wrong, I'm regarding it as a bugfix rather than as a breaking change.

fix: double variation was returning ints

---

release-please-config.json

Now that both server 3.0 and redis-source 1.0 are released, these fields should be removed.

ci: remove 'release-as' from server and server-redis-source

---

.github/workflows/release-please.yml

Was missing `-` in the `release-please` job outputs, which meant that the redis source release job isn't running when we merge a release PR.

ci: fix automatic releases of redis source

---

libs/common/include/launchdarkly/config/shared/builders/events_builder.hpp
libs/common/include/launchdarkly/config/shared/built/events.hpp
libs/common/src/config/events_builder.cpp
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h
libs/server-sdk/src/bindings/c/builder.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp

This adds a missing C binding for configuring the context key cache capacity which the Event Processor uses to deduplicate index events.

feat(event-processor): add C binding for context keys cache capacity

---

libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h

The docs said milliseconds, but the parameter is seconds.

docs: fix incorrect time unit on LDServerDataSourcePollBuilder_IntervalS

---

libs/server-sdk-redis-source/include/launchdarkly/server_side/integrations/redis/redis_source.hpp
libs/server-sdk-redis-source/src/redis_source.cpp
libs/server-sdk-redis-source/tests/redis_source_test.cpp

Previously, `RedisDataSource::Create` returned an `expected<shared_ptr<RedisDataSource>, error>`.
The idea was that `DataSystem` config accepts a `shared_ptr` (in theory, so that they don't have to give up management of the source's lifetime. TBD if this turns out to be helpful or not.)
We don't need to force the user into shared ownership in the factory function though - instead, return a `unique_ptr` and let them make the transformation.
Motivation is that`shared_ptr` is painful with the C bindings. We get back a stack-allocated `shared_ptr` from the factory, and then need to heap allocate one so we cast it to the opaque type. This is not necessary if we just return a `unique_ptr`, since we can call `.release()` and then pass the unmanaged pointer around.

feat!: RedisDataSource::Create should return unique_ptr instead of shared_ptr

---

examples/hello-cpp-server-redis/main.cpp
libs/server-sdk-redis-source/include/launchdarkly/server_side/bindings/c/integrations/redis/redis_source.h
libs/server-sdk-redis-source/include/launchdarkly/server_side/integrations/redis/redis_source.hpp
libs/server-sdk-redis-source/src/CMakeLists.txt
libs/server-sdk-redis-source/src/bindings/redis/redis_source.cpp
libs/server-sdk-redis-source/src/redis_source.cpp
libs/server-sdk-redis-source/tests/c_bindings_test.cpp
libs/server-sdk-redis-source/tests/redis_source_test.cpp
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/lazy_load_builder/lazy_load_builder.h
libs/server-sdk/include/launchdarkly/server_side/config/builders/data_system/lazy_load_builder.hpp
libs/server-sdk/include/launchdarkly/server_side/config/built/data_system/lazy_load_config.hpp
libs/server-sdk/src/bindings/c/builder.cpp
libs/server-sdk/src/config/builders/data_system/lazy_load_builder.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp

This adds C bindings for creating a Redis Source, as well as a LazyLoad config method to accept pointers to the C type representing an instantiated Redis Source.
Demo:
```c
LDServerLazyLoadBuilder lazy_builder = LDServerLazyLoadBuilder_New();
struct LDServerLazyLoadRedisResult out_result;
if (!LDServerLazyLoadRedisSource_New(uri, prefix, &out_result))
printf("%s\n", out_result.error_message);
exit(1);
}
LDServerLazyLoadBuilder_SourcePtr(lazy_builder, out_result.source);
LDServerConfigBuilder_DataSystem_LazyLoad(cfg_builder, lazy_builder);
```

feat: redis data source C bindings

---

libs/common/include/launchdarkly/bindings/c/context.h
libs/common/src/bindings/c/context.cpp
libs/common/tests/bindings/context_test.cpp

Adds `LDContext_CanonicalKey`. Noticed this missing when writing Lua binding. 
We're also missing a way of returning `Context::Kinds`, but that would involve adding a new iterator. This gets the job done for testing.

feat: add C binding for Context::CanonicalKey()

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/common/include/launchdarkly/detail/c_binding_helpers.hpp
libs/server-sdk-redis-source/tests/c_bindings_test.cpp
libs/server-sdk-redis-source/tests/prefixed_redis_client.hpp
libs/server-sdk-redis-source/tests/redis_source_test.cpp
libs/server-sdk/include/launchdarkly/server_side/bindings/c/all_flags_state/all_flags_state.h
libs/server-sdk/src/bindings/c/all_flags_state/all_flags_state.cpp
libs/server-sdk/src/client_impl.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp

Adds `LDAllFlagsState_Map(state)`, which returns a map of key/value pairs encoded in an object-type `LDValue`. This is in contrast to accessing individual values in the state.

feat: add LDAllFlagsState_Map C binding

---

libs/common/include/launchdarkly/bindings/c/array_builder.h
libs/common/include/launchdarkly/bindings/c/config/logging_builder.h
libs/common/include/launchdarkly/bindings/c/context.h
libs/common/include/launchdarkly/bindings/c/context_builder.h
libs/common/include/launchdarkly/bindings/c/flag_listener.h
libs/common/include/launchdarkly/bindings/c/listener_connection.h
libs/common/include/launchdarkly/bindings/c/memory_routines.h
libs/common/include/launchdarkly/bindings/c/object_builder.h
libs/common/include/launchdarkly/bindings/c/status.h
libs/common/include/launchdarkly/bindings/c/value.h

Doxygen has issues when we've got an `LD_EXPORT` on the same line as the function name. 
I fixed a bunch of those, and then also update a bunch of doc references to use autogenerated links. More work can be done on an as-needed basis.

docs: fix a bunch of broken Doxygen links

---

libs/internal/src/encoding/sha_1.cpp
libs/internal/src/encoding/sha_256.cpp

The `SHA1_*` family of functions were [deprecated](https://www.openssl.org/docs/man3.1/man3/SHA1_Init.html) in OpenSSL 3.0, but plain old `SHA1` is not.
I don't see a reason to _not_ use these functions - we aren't incrementally hashing something, so the 3 step process doesn't seem to benefit us.

refactor: remove deprecated usage of OpenSSL SHA1_ and SHA256_ functions

---

.github/actions/install-boost/action.yml

The current boost version for Windows is floating, and it recently updated to Boost 1.84. That's a problem because our boost download path is hardcoded since there isn't an easy way to obtain it from `choco`. 
This pins to 1.81 just like the Linux build.

ci: pin boost 1.81 on Windows CI

---

PROVENANCE.md
libs/client-sdk/README.md
libs/server-sdk-redis-source/README.md
libs/server-sdk/README.md

Drafting up documentation for how consumers may use the SLSA framework to verify SDK packages published with provenance to improve supply chain security.

docs: adding SLSA verification steps for cpp-server-sdk

---

.github/actions/install-boost/action.yml
.github/actions/install-openssl/action.yml

It appears the OpenSSL 3.2 release removed some functionality that was in 3.1, which Boost.Asio relied on. 
Not sure if it's actually OpenSSL 3.2 that did it, or the chocolatey packaging process. 
In any case, CI will fail on Windows until either this is pinned to 3.1.1 or we bump Boost (which may have a fix 🤷‍♂️ ).
```
error LNK2019: unresolved external symbol EVP_PKEY_is_a referenced in function "public: class boost::system::error_code __cdecl boost::asio::ssl::context::use_rsa_private_key(class boost::asio::const_buffer const &,enum boost::asio::ssl::context_base::file_format,class boost::system::error_code &)" (?use_rsa_private_key@context@ssl@asio@boost@@QEAA?AVerror_code@system@4@AEBVconst_buffer@34@W4file_format@context_base@234@AEAV564@@Z)
launchdarkly-cpp-server.lib(asio.cpp.obj) …
```

ci: pin OpenSSL to 3.1.1 on Windows

---

libs/server-sdk/include/launchdarkly/server_side/all_flags_state.hpp
libs/server-sdk/src/evaluation/bucketing.hpp
libs/server-sdk/src/evaluation/detail/semver_operations.hpp
libs/server-sdk/src/evaluation/evaluation_error.hpp

On our existing test systems (ubuntu, mac, windows), <cstdint> is included via other system headers such that compilation succeeds.
On Arch, this isn't the case.

fix: add missing <cstdint> in various headers

---

libs/client-sdk/src/CMakeLists.txt
libs/common/src/CMakeLists.txt
libs/internal/src/CMakeLists.txt
libs/server-sdk-redis-source/src/CMakeLists.txt
libs/server-sdk/src/CMakeLists.txt
libs/server-sent-events/src/CMakeLists.txt

See: https://github.com/launchdarkly/cpp-sdks/issues/369
We're currently setting this variable explicitely. According to CMake docs, users can instead set `CMAKE_MSVC_RUNTIME_LIBRARY`: 
> This variable is used to initialize the [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html#prop_tgt:MSVC_RUNTIME_LIBRARY) property on all targets as they are created.
If it's not set, then:
> If this variable is not set then the [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html#prop_tgt:MSVC_RUNTIME_LIBRARY) target property will not be set automatically. If that property is not set then CMake uses the default value **MultiThreaded$<$<CONFIG:Debug>:Debug>DLL** to select a MSVC runtime library. …

build: do not set MSVC_RUNTIME_LIBRARY

---

libs/internal/src/serialization/json_evaluation_result.cpp

**Background**
When the client-side SDK is deserializing an evaluation result, it may encounter a `null` evaluation value for a particular flag. That is, the value is literally `null` in JSON.
It might also receive an evaliuation result with an _omitted_ value. Some server-side SDKs may produce this because they don't treat null/missing as equivalent. 
**Problem**
In that case, the client-side SDK would throw a schema error. This isn't correct since producing a null/omitted value is legitimate. 
**Solution**
The deserialization code now takes into account the equivalence of null/omission and doesn't throw an error.

fix: handle omitted evaluation result value when deserializing client-side JSON payload

---

.github/workflows/release-please.yml
release-please-config.json

Bumps release-please to v4, removing explicit `manifest` command.

ci: upgrade to release-please v4

---

CMakeLists.txt
cmake/googletest.cmake

This upgrades googletest to a much more recent commit. The intention is to see if it helps with the `DEADLYSIGNAL` issue that has been plaguing this repo's CI for the last couple weeks. 
Underlying theory is that possibly there is some incompatibilitiy between the old googletest and gcc.

ci: upgrade googletest

---

.github/workflows/manual-sdk-release-artifacts.yml
.github/workflows/release-please.yml

Provenance generation fails due to Rekor public key errors were identified as a known issue and fixed in version 1.10.0 per: https://github.com/slsa-framework/slsa-github-generator/issues/3350

build: bumping slsa-github-generator version to resolve issue with retrieving Rekor public keys

---

libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/client_impl.cpp
libs/server-sdk/src/evaluation/evaluation_stack.cpp
libs/server-sdk/src/evaluation/evaluation_stack.hpp
libs/server-sdk/src/evaluation/evaluator.cpp
libs/server-sdk/src/evaluation/evaluator.hpp
libs/server-sdk/src/evaluation/rules.cpp
libs/server-sdk/src/evaluation/rules.hpp
libs/server-sdk/tests/evaluation_stack_test.cpp
libs/server-sdk/tests/evaluator_tests.cpp
libs/server-sdk/tests/rule_tests.cpp

fix: Evaluate should not share EvaluationStack between calls

---

libs/client-sdk/include/launchdarkly/client_side/client.hpp
libs/server-sdk/include/launchdarkly/server_side/client.hpp

Since modifying the `StartAsync` method (which returns a future) would be a significant change to the API, we're adding docs instead to call out the "don't block indefinitely" scenario.

docs: call out indefinite blocking scenerio on StartAsync method

---

libs/client-sdk/src/data_sources/data_source_event_handler.cpp
libs/client-sdk/src/flag_manager/flag_persistence.cpp
libs/client-sdk/tests/context_index_test.cpp
libs/internal/src/serialization/json_primitives.cpp
libs/server-sdk/src/data_systems/background_sync/sources/polling/polling_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/event_handler.cpp
libs/server-sdk/src/integrations/data_reader/kinds.cpp

The latest Boost 1.85 release has deprecated usage of `boost::json::error_code`, and since that causes warnings, our CI fails (since we have warnings-as-errors in CI.)
That type was just an alias for `boost::system::error_code`, so I've done a find and replace.

refactor: replace boost::json::error_code with boost::system::error_code

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/config/builder.h
libs/client-sdk/include/launchdarkly/client_side/bindings/c/config/config.h
libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/common/include/launchdarkly/bindings/c/export.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/config.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/sdk.h

When `LD_EXPORT` appears on the same line as the function name, Doxygen doesn't render the function name nicely and it's confusing.
This fixes a bunch of instances that I found in the C bindings.

docs: improve Doxygen rendering on C bindings

---

contract-tests/client-contract-tests/src/entity_manager.cpp
contract-tests/client-contract-tests/src/main.cpp
contract-tests/data-model/include/data_model/data_model.hpp
contract-tests/server-contract-tests/src/entity_manager.cpp
contract-tests/server-contract-tests/src/main.cpp
libs/client-sdk/include/launchdarkly/client_side/bindings/c/config/builder.h
libs/client-sdk/src/bindings/c/builder.cpp
libs/client-sdk/src/client_impl.cpp
libs/client-sdk/src/data_sources/polling_data_source.cpp
libs/client-sdk/src/data_sources/streaming_data_source.cpp
libs/client-sdk/tests/client_config_test.cpp
libs/common/include/launchdarkly/config/shared/builders/http_properties_builder.hpp
libs/common/include/launchdarkly/config/shared/built/http_properties.hpp
libs/common/src/config/http_properties.cpp
libs/common/src/config/http_properties_builder.cpp
libs/internal/include/launchdarkly/events/detail/request_worker.hpp
libs/internal/include/launchdarkly/events/detail/worker_pool.hpp
libs/internal/include/launchdarkly/network/asio_requester.hpp
libs/internal/src/events/asio_event_processor.cpp
libs/internal/src/events/request_worker.cpp
libs/internal/src/events/worker_pool.cpp
libs/internal/tests/event_processor_test.cpp
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h
libs/server-sdk/src/bindings/c/builder.cpp
libs/server-sdk/src/client_impl.cpp
libs/server-sdk/src/data_systems/background_sync/sources/polling/polling_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.cpp
libs/server-sdk/tests/server_c_bindings_test.cpp
libs/server-sent-events/include/launchdarkly/sse/client.hpp
libs/server-sent-events/src/client.cpp

This adds a new config builder option, `CustomCAFile` and associated C binding to the server and client SDKs.
When specified, the SDK's streaming, polling, and event connections will verify its TLS peer based on the CAs found in this file. The custom file may be un-set by passing an empty string. 
We could instead make empty string be a configuration error, but it would involve changing the signature for the `Build()` methods of the HTTPs properties + TLS properties builders. That might be a safer default, although potentially less convenient.

feat: specify a custom CA file for TLS peer verification

---

libs/internal/include/launchdarkly/events/detail/summarizer.hpp
libs/internal/tests/event_summarizer_test.cpp

This is a soundness bug that was detected by MSVC in debug configuration.
The `Summarizer::VariationKey` has `==` and `<` operators. 
In the case of `<`, the comparison wasn't properly handling the case where `this->variation` was greater than the parameter. In that case, it would fall back to comparing `this->version` which is incorrect (should only happen if the variations are equal.)
This could have affected the JSON serialization of the summary counters, mainly the order in which the array was serialized. I'm wondering if it could also caused bugs in actual counts. `std::map` uses the `<` operator to determine key equality.

fix: Summarizer::VariationKey operator< was unsound

---

libs/internal/tests/ld_logger_test.cpp

Test uses `std::remove_if` which is found in the`<algorithm>` header. It happens that our compilers/configuration doesn't need it, but others do.

test: add <algorithm> header to logging_c_binding_test.cpp

---

libs/client-sdk/include/launchdarkly/client_side/client.hpp
libs/server-sdk/include/launchdarkly/server_side/client.hpp

The `Client` types that follow pimpl idiom had warnings that they needed to define destructors as well to satisfy the rule of five.
We don't need to define move/copy/copy-assign/move-assign for these at all, instead we can follow the rule of zero since the only member is a `std::unique_ptr`.

refactor: only define constructors for Client types

---

contract-tests/sse-contract-tests/src/event_outbox.cpp
libs/client-sdk/src/data_sources/streaming_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.cpp
libs/server-sent-events/include/launchdarkly/sse/error.hpp
libs/server-sent-events/src/CMakeLists.txt
libs/server-sent-events/src/client.cpp
libs/server-sent-events/src/error.cpp

This commit pulls the stringification logic of SSE errors into the SSE package itself, and refactors the enum into a richer sum type using `std::variant`.

fix: more helpful error messages for streaming connection failures

---

.github/workflows/release-please.yml
PROVENANCE.md

The `client`, `server`, and `server-redis` provenance generation workflows each create a `{windows,linux,macos}-multile-provenance.intoto.jsonl` file that gets uploaded to the respective tagged releases. However, in an intermediate step, these files are temporarily uploaded to the workflow workspace that's shared between all three release types. Very occasionally, a race condition happens where one release type will overwrite the provenance file for the other release type before it's able to download it and upload it to the appropriate tagged release, which results in a SLSA verification error. 
This quick fix to prefix the provenance files with the release type should remove this overlap/conflict/race condition.

build: fixing overlap in provenance filenames that causes race condition with multiple provenance generation jobs

---

.github/workflows/hello-apps.yml
scripts/run-hello-apps.sh

With the addition of the new `LD_BUILD_EXPORT_ALL_SYMBOLS`, we can easily build & run the `hello-cpp-*` binaries in CI. 
Although we don't build these libs for distribution (could cause ABI issues), building them from source in this type of configuration should be supported and tested.

ci: allow example cpp apps to be dynamically linked

---

libs/server-sdk-redis-source/include/launchdarkly/server_side/bindings/c/integrations/redis/redis_source.h
libs/server-sdk-redis-source/tests/redis_source_test.cpp

This adds a complete example to our C bindings for the Redis source.

docs: add code example for setting up Lazy Load Redis source in C

---

libs/client-sdk/src/data_sources/streaming_data_source.cpp
libs/client-sdk/src/data_sources/streaming_data_source.hpp
libs/internal/include/launchdarkly/data_sources/data_source_status_manager_base.hpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.cpp
libs/server-sdk/src/data_systems/background_sync/sources/streaming/streaming_data_source.hpp
libs/server-sent-events/include/launchdarkly/sse/error.hpp
libs/server-sent-events/src/client.cpp
libs/server-sent-events/src/error.cpp

The existing handling for data source state transitions when receiving `sse` errors was incorrect. It was treating any error as a state transition to `kOff/kShutdown`, and logging at the `error` level.
The correct behavior would be making that transition only if the error is unrecoverable. Additionally, recoverable errors should be logged at the debug level, in order to not overstate the impact of the issue.
This bug did not actually affect the backoff behavior of the eventsource, but it did impact any status listeners which was certainly misleading.

fix: improve handling of streaming error state changes/logging

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/client-sdk/include/launchdarkly/client_side/data_source_status.hpp
libs/client-sdk/src/bindings/c/sdk.cpp
libs/client-sdk/src/data_sources/data_source_status.cpp
libs/client-sdk/tests/client_c_bindings_test.cpp

We were missing a convenient way to convert a data source status's state variable to a string. This is useful in logging and debugging applications.
While adding this, I also applied the "ensure C enum is at least 32 bits wide" treatment that has been done in the past on the LogLevel enum.

feat: add client-side C binding for fetching data source state

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/config/builder.h
libs/common/include/launchdarkly/bindings/c/context_builder.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/config/builder.h

We've had multiple issues filed for accessing builders that have already been consumed. Our docs need to be more prescriptive on this issue.

docs: add warning for accessing builders after consumption

---

libs/server-sdk/src/data_systems/lazy_load/lazy_load_system.hpp

This improves the caching behavior of the Lazy Load data system.
Previously, calling `AllFlags` or `AllSegments` updated an "allFlags" or "allSegments" key in the unscoped freshness tracker. That's correct, as those keys act as rate limiters for the "all" queries.
It then upserted each individual item in the _unscoped_ freshness tracker.
This is not optimal, as the unscoped tracker is not referenced when we read individual items. This results in cache misses for individual items, even after they were all refreshed. 
This change properly adds the individual items into the scoped tracker. Now, `AllFlags` or `AllSegments` should result in "priming" the cache for future individual item fetches.
This does have the behavior of syncing the TTL dates of all items to a single point in time. …

fix: improve caching behavior of database integration

---

.github/actions/cmake-test/action.yml
.github/workflows/cmake.yml
CMakeLists.txt
cmake-tests/CMakeLists.txt
cmake-tests/README.md
cmake-tests/declareProjectTest.cmake
cmake-tests/test_add_subdirectory/CMakeLists.txt
cmake-tests/test_add_subdirectory/project/CMakeLists.txt
cmake-tests/test_add_subdirectory/project/main_client.cpp
cmake-tests/test_add_subdirectory/project/main_server.cpp
scripts/build-cmake-integration-tests.sh
scripts/configure-cmake-integration-tests.sh

This is the first in a series of PRs that adds cmake integration tests to CI. 
The purpose of these tests is to validate that a test application can incorporate the LaunchDarkly SDKs via cmake.
The tests are organized by incorporation method. This first test is for `add_subdirectory`, which is currently the only supported way of using the SDK. 
When I add `find_package` support, I'll add tests for that here.

ci: basic add_subdirectory cmake integration test

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/sdk.h
libs/server-sdk/include/launchdarkly/server_side/bindings/c/sdk.h

This adds a couple more code examples to the server-side C bindings, so it's easier to get started using the SDK's methods. 
It's not complete. but I'd like to merge it to get some incremental value, and continue with more PRs in the future.

docs: add some examples to server-side C bindings

---

.github/workflows/client.yml
.github/workflows/server.yml
.github/workflows/sse.yml

Noticed the dreaded "could not find release matching v2.." on the SSE package on a recent commit. Found that I missed updating the SSE client's CI configuration when I bumped the other packages.

ci: bump contract-tests action to 1.1.0

---

libs/server-sent-events/src/CMakeLists.txt
libs/server-sent-events/src/backoff.cpp
libs/server-sent-events/src/backoff.hpp
libs/server-sent-events/src/backoff_detail.cpp
libs/server-sent-events/src/backoff_detail.hpp
libs/server-sent-events/tests/backoff_test.cpp

In some platform configurations, the SSE backoff calculation overflows which results in failing to schedule another backoff attempt via `asio::deadline_timer::expires_from_now`.
This PR refactors the backoff algorithm to use free functions which can be independently tested. 
It fixes the bug by constraining the maximum backoff exponent based on the configurable max backoff parameter. 
Finally, I've added some test vectors for large attempt values. In the bug report, the overflow happens at about 34 minutes which corresponded to 55 attempts.

fix: guard against overflow in sse backoff calculation

---

libs/client-sdk/include/launchdarkly/client_side/bindings/c/config/builder.h

This commit provides better documentation for how to initialize the `LDPersistence` struct. 
The existing docs were ambiguous as to when the call should be made. If you call _after_ setting custom pointers, then the custom pointers will be wiped out.

docs: make usage of LDPersistence_Init clearer

---

.github/actions/install-openssl/action.yml

This bumps OpenSSL from 3.1.1 to 3.4.0 on Windows ([the latest, released two days ago](https://github.com/openssl/openssl/releases/tag/openssl-3.4.0)). This will resolve outstanding CVEs filed against 3.1.1.

fix(deps): build with openssl 3.4.0 on windows

---

contract-tests/server-contract-tests/src/main.cpp
libs/internal/include/launchdarkly/events/data/common_events.hpp
libs/internal/include/launchdarkly/events/data/events.hpp
libs/internal/include/launchdarkly/events/event_processor_interface.hpp
libs/server-sdk/include/launchdarkly/server_side/all_flags_state.hpp
libs/server-sdk/src/CMakeLists.txt
libs/server-sdk/src/all_flags_state/all_flags_state.cpp
libs/server-sdk/src/all_flags_state/json_all_flags_state.cpp
libs/server-sdk/src/client_impl.cpp
libs/server-sdk/src/events/event_factory.cpp
libs/server-sdk/src/prereq_event_recorder/prereq_event_recorder.cpp
libs/server-sdk/src/prereq_event_recorder/prereq_event_recorder.hpp
libs/server-sdk/tests/all_flags_state_test.cpp
libs/server-sdk/tests/prereq_event_recorder_test.cpp

Updates the `AllFlags()` API to gather and expose prerequisite information for flags. 
The prereqs are available via `State::Prerequisites()`, and are more importantly serialized in the JSON representation of the bootstrap payload. 
The implementation strategy was to create a custom `IEventProcessor` specifically for `AllFlags` usage. Previously, `AllFlags` invoked the evaluator with a no-op `EventScope`, which made event creation a no-op within the eval algorithm.
This change now passes in a `PrereqEventRecorder` which tracks the top-level prerequisites of each flag.

feat: expose prerequisite relations in AllFlags API

---

.github/workflows/client.yml
.github/workflows/cmake.yml
.github/workflows/hello-apps.yml
.github/workflows/manual-sdk-release-artifacts.yml
.github/workflows/release-please.yml
.github/workflows/server-redis.yml
.github/workflows/server.yml

MacOS 12 executors are deprecated and will cease operation in December. Github randomly failed some jobs today during a "brownout" to let us know about this. 
Very effective I must say.

ci: upgrade mac executors to macos-13

---

examples/CMakeLists.txt
examples/hello-c-server-redis/CMakeLists.txt
examples/hello-c-server-redis/main.c

We had a ready-to-go example for C++, but the only good example for C was buried in a unit test. I've extracted that out into a buildable hello-example.

chore: add C binding example for server-side Redis Source

---

.github/actions/install-boost/action.yml
libs/client-sdk/src/flag_manager/flag_updater.cpp
libs/client-sdk/tests/flag_updater_test.cpp

The store should be updated before events are dispatched to ensure consistent data between event information and variation calls.

fix: Change notification consistency.

---

.github/actions/install-openssl/action.yml

The daily builds have been failing when trying to download OpenSSL 3.4.1. The package maintainer removes older versions with security vulnerabilities. This bumps to the latest 3.5 version. The package maintainer provides a 3.4.2 but chocolatey does not.

chore: Update OpenSSL for CI
